services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - inventory

  composer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-composer
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["composer"]
    networks:
      - inventory

  web:
    image: nginx:alpine
    container_name: inventory-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - inventory

networks:
  inventory:
    driver: bridge
